### ISSUE TITLE
Add support for python3.8

### ISSUE THREAD

**Issue by laurentS** [terminusdb/terminusdb-client-python#120]
**Is your feature request related to a problem? Please describe.**
As python 3.8 is the current "stable" version, would it make sense to add CI tests for it? I've run the test suite locally on it, and it all passes, so I think it's just a matter of adding the version to `.travis.yml`.

**Describe the solution you'd like**
Just have the CI tests run for python 3.8 to give confidence that this version is supported

**Additional context**
I'm happy to send a PR for it :)

**Comment by Cheukting** [comment]
Good spot, I was talking with Robin the other day that we should in test python 38 in Travis, I will add it in this week.

**Comment by Cheukting** [comment]
It is now added in commit 86955c378db3d216d1675392370a69239e942cf8
