### ISSUE TITLE
Add type annotations?

### ISSUE THREAD

**Issue by laurentS** [terminusdb/terminusdb-client-python#121]
**Is your feature request related to a problem? Please describe.**
I have been looking at the code to try and understand how some functions work, and as often with python it is difficult to guess what sort of data is expected in a variable or function call.

**Describe the solution you'd like**
Python type hints are a great way to provide such info. I see them as automated documentation, which also serves as a debugging help. Given how strong the data typing is inside the database, I think it would also make sense to extend it over to the client code.

**Describe alternatives you've considered**
I am not aware of any alternatives to type hints, but I think they can be implemented in a couple of different ways:
- directly into the code, probably the goal in the end, given how they help with understanding the code
- as `*.pyi` stub files that live side by side with the actual code, or even in a different repo. I think they have value in code bases that also aim at working under older python version (2.7 and so on), but given that you're aiming for python 3.6+, I don't think this applies. They're also useful if you don't want to include hints in the main code base, as the stubs can live their own life elsewhere (and constantly try to stay up to date with the code).

**Additional context**
When I've added type hint to existing code bases before, I've almost always found a couple of bugs that `mypy` made immediately obvious. Some argue that type hints make the code harder to read, but I think it's a minor disagreement considering the value they bring.
I could be up for sending a PR with annotations for the core functions, if you think that would be useful.

**Comment by itsvinayak** [comment]
@laurentS are you working on it, I would also like to work on this issue. if you are already working. Is there anything I can do?

Thank you,
@itsvinayak

**Comment by laurentS** [comment]
H @itsvinayak ! No, unfortunately, I haven't been able to yet. I might be able to make some time for it next week, but if you're able to start before that, please go ahead!
I think it would also be worth hearing what @Cheukting thinks about how to do this (stubs VS in-code).

**Comment by itsvinayak** [comment]
sure, I have tried some implementation in #141

**Comment by Cheukting** [comment]
Hi, @laurentS and @itsvinayak I have started adding type hinting in the new code that I am developing. If anyone wants to try adding type hinting to the other files that would be great! I think it's not a one-person job so please feel free to take WOQLQuery, WOQLClient or WOQLDataFrame to work on. Just let us know (by commenting here) which one you are working on.

For the stub files, I have no thought about adding them yet but will have a look.

**Comment by Cheukting** [comment]
Update on what needed to add type annotation:

- [woqlClient.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqlclient/woqlClient.py)
- [woql_query.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqlquery/woql_query.py)
- [woql_library.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqlquery/woql_library.py)
- [woqlDataframe.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqldataframe/woqlDataframe.py)
- [woql_view.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqlview/woql_view.py)

To help us:

1. pick one of the file that you want to work on. 🤔
2. Check if there's anyone working on the same thing in the comment below 👇🏻
3. State which file you are working on in the comment below. If you want to only work for part of the file, specifically state which methods that you are taking.
4. Type annotating away!
5. Run `tox -e check` to check the code formating
6. (optional) try generate the docs locally to see if the type annotation is registered by sphinx

When you send in the PR, link to this issue by adding see #121 in the comment of the PR

**Please send the PR to master branch**

**Comment by KarenImmanuel** [comment]
Hey,
I can work on annotating one of the files.

Maybe I can start with the last file **woql_view.py**?

**Comment by vipulgarg1** [comment]
Hey Everyone,
I am starting Working on type annotation for [woqlDataframe.py](https://github.com/terminusdb/terminusdb-client-python/blob/master/terminusdb_client/woqldataframe/woqlDataframe.py)

**Comment by GavinMendelGleason** [comment]
That's great vipulgarg1. 

In terms of this, it would be useful if the WOQL result object returned an ordered list of xsd types to go along with the ordered list of column names it currently returns. I can implement this feature in server if it will help.

**Comment by vipulgarg1** [comment]
Ok Sure @GavinMendelGleason .I will take care of that and if have any questions will post it here.

**Comment by laurentS** [comment]
Hi all, I've picked up `woqlClient.py` and I'm adding annotations to it.
