### ISSUE TITLE
Fixing typos and broken links in README.md

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#122]
The README.md needs some love ❤️ and maintenance 🔧 .

TODO:

- [ ]  fixing typos (I am sure there's some 😅 )

- [ ] fixing broken links for the tutorial, the new one should point to the bike tutorial at the tutorial repo: https://github.com/terminusdb/terminus-tutorials/tree/master/bike-tutorial/python

- [ ] adding a session and a link to RELEASE_NOTES.md

- [ ] (optional) adding anything that you think will improve the README.md

**Comment by mts310** [comment]
Hi I've forked this and will begin work on the README.

**Comment by mts310** [comment]
@Cheukting - the README on the master branch seems to be more recently updated than on the dev branch. I am planning to make a new branch from the master, correct typos, then pull to dev - but just wanted to double check that sounds okay to you.

**Comment by Cheukting** [comment]
> @Cheukting - the README on the master branch seems to be more recently updated than on the dev branch. I am planning to make a new branch from the master, correct typos, then pull to dev - but just wanted to double check that sounds okay to you.

@mts310 branching from and sending the PR to master is fine. You don't have to merge dev into it. There's some work in dev
 that is supposed to wait for the next release. Thanks

**Comment by Cheukting** [comment]
Thanks @mts310 :-)
