### ISSUE TITLE
Adding one basic usage of WOQLClient and one basic usage of WOQLQuery in README 

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#125]
Now the [usage session of the README](https://github.com/terminusdb/terminusdb-client-python#usage) only points people to the documentation. 😞

It would be great to give people an idea what terminusdb_client can do before leading them into the docs. 😉

1) one basic usage of WOQLClient:
    - [ ] could be creating a database
    - [ ] could be connecting to an existing database
2) one basic usage of WOQLQuery
    - [ ] could be creating a simple schema 
    - [ ] could be making a simple query to a database with data

You have some flexibility here about what you can do. If you are new to the library, see the [tutorial here](https://github.com/terminusdb/terminus-tutorials/blob/master/bike-tutorial/python/bike-tutorial.py) to set some ideas. 💡

**Comment by Darshnadas** [comment]
Hey, @Cheukting I am looking for a good first issue as I am a beginner in contributions. I would like to work on this issue.

**Comment by Cheukting** [comment]
> Hey, @Cheukting I am looking for a good first issue as I am a beginner in contributions. I would like to work on this issue.

No problem, it's a good one to start
