### ISSUE TITLE
WOQLQuery().vars()

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#127]
We would like to have a way of generating variables to be used in WOQLQueries quickly.  Here is what we should do:

1) This is a new feature so clone and branch from the ****dev**** branch

2) Add a new methods `vars` in WOQLQuery that takes in a various number of variables which are `str`, add "v:" in front of all of them then return them. (check the [JS client equivalent here](https://github.com/terminusdb/terminusdb-client/blob/78c589c36d79e788d17fc2ae7d5090f67c97931b/lib/woql.js#L857) as reference)

3) Write unit test(s) for it

4) When you are happy with your code and test(s), run `tox` to lint it and test everything. You may have to make some changes to pass flake8

5) Make a PR to the ****dev**** branch (you can link to this issue by adding `closes #127` in your PR's comment)

**Comment by Sangarshanan** [comment]
Picking this up :hand:

**Comment by Cheukting** [comment]
Thanks @Sangarshanan
