### ISSUE TITLE
Usage Examples buried/nonexistent

### ISSUE THREAD

**Issue by bionicles** [terminusdb/terminusdb-client-python#133]
**Describe the bug**
There are no CRUD examples in the Readme or the front of the docs

**To Reproduce**
Evaluate the product as a new user

**Expected behavior**
A basic code block in the README with installation, setup, creation of a new database, CRUD operations

**Error logs**
MissingDocumentException

**System information (please complete the following information):**
 - OS: Human Brain

**Additional context**
When I look at a database and don't see usage examples, I just move on to evaluate the next database

**Comment by Cheukting** [comment]
see #125

**Comment by Cheukting** [comment]
It would be great to include a usage example in the documentation page here (https://terminusdb.github.io/terminusdb-client-python/index.html) as well.

To add it, edit the index.rst (https://github.com/terminusdb/terminusdb-client-python/blob/master/docs/source/index.rst)
