### ISSUE TITLE
Create a wiki for to help contributors 

### ISSUE THREAD

**Issue by Pradhvan** [terminusdb/terminusdb-client-python#138]
A [wiki](https://guides.github.com/features/wikis/#creating-your-wiki) with good detailed instructions for developer setup instructions:
1. Fork the project
2. Create a branch
3. Make init uses `pipenv` so you don't need to create a separate virtual env
4. Work on the changes
5. Create PR. 

Somewhat these instructions, setup instructions for different OS and env that links to `terminusdb` quick start and where they can start contributing etc. 

I guess it would be very useful for first-time contributors.

**Comment by Pradhvan** [comment]
I would be happy to take this up 😄

**Comment by kevinchekovfeeney** [comment]
Go for it - sounds wonderful!

**Comment by Pradhvan** [comment]
@Cheukting I started to work on this issue and realized that Github doesn't support a PR based system for a wiki[0].

So I was thinking to make changes into the existing [Contributing.md](https://github.com/terminusdb/terminusdb-client-python/blob/master/Contributing.md) that the project has. That way it would be easier to review and maintian. 

[0]https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by Cheukting** [comment]
Ah! it's a shame, however, if you want me to set up like this: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html I am happy to do so. @Pradhvan Let me know what do you think :-)

**Comment by Pradhvan** [comment]
@Cheukting yes, if you can set it up that would be really helpful. 😄

**Comment by Cheukting** [comment]
You can now contribute to [terminusdb/terminusdb-client-python-wiki](https://github.com/terminusdb/terminusdb-client-python-wiki)
