### ISSUE TITLE
Writing test for woql_view.py

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#148]
We need to add tests for woql_view.py, a file named `test_woqlView.py` can be added to `terminusdb_client/tests/`

In the test, it would check the WOQLView methods against the js_config, for example, test for `WOQLView().height(100)` should give you `woqlGraphConfig.height(100)` when you call the `print_js_config`.

The issue would need more guidance so please don't feel shy to ask for clarification here.

**PR should be made to master branch**

**Comment by gnurenga** [comment]
@Cheukting Will work on this could you assign this task to me.

**Comment by i-karen** [comment]
Hey @Cheukting, @gnurenga , I can also work on this as I added annotations for WOQLView().

But, not sure if we need multiple contributors here!

**Comment by gnurenga** [comment]
Hi @Cheukting,  Since I was occupied with my official work I could not able to contribute.

Since @i-karen is coming forward to help. I am ok to withdraw from this task. You can assign it to @i-karen. 

Sorry for the delay in this update.

**Comment by Cheukting** [comment]
@i-karen do you want to take it or someone else please help :-) Say it below

**Comment by i-karen** [comment]
Yes, I can work on this!

I can send a test PR and ask for clarifications.

**Comment by Pradhvan** [comment]
If no one is working on it, I would be happy to look into it this weekend. 😄

**Comment by Cheukting** [comment]
> If no one is working on it, I would be happy to look into it this weekend. 😄

Sure @Pradhvan, that's very welcomed. I believe we don't have proper tests for woql_view yet. Let me know if you have any questions :-)

**Comment by Pradhvan** [comment]
@Cheukting I was checking out the [docs](https://terminusdb.github.io/terminusdb-client-python/woqlView.html) but could not understand what's `woql_view.py` is meant to do. Can you please share some examples so it's easy for me to write tests for it?

**Comment by Cheukting** [comment]
It let you generate a graph representation like [this](https://terminusdb-labs.github.io/dbpedia-hackathon-autumn-2020/all_polities_and_conflicts.html). I think I have done a demo in JupyterCon, the talk recording is [here](https://youtu.be/fclLpp9U8aw). Let me know if you have more questions, I am happy to work with you on this.

**Comment by Pradhvan** [comment]
Let me check out the talk, thanks for sharing @Cheukting 

I did not find `test_woql_view.py` in the test directory so I guess I would need to create that too.

**Comment by Pradhvan** [comment]
@Cheukting this might be a silly question but is there a small open dataset that I use with terminusdb to test out the generate a graph and play around with the `woql_view`?

**Comment by Cheukting** [comment]
Sure @Pradhvan, I have added the example use of WOQLView in the [bike example here](https://github.com/terminusdb/terminusdb-tutorials/blob/master/bike-tutorial/python/Create%20TerminusDB%20Graph%20with%20Python%20Client.ipynb). You can skip creating the db and loading the data if you clone the "pybike" from TerminusHub

**Comment by Pradhvan** [comment]
Thanks, @Cheukting will look into it. 😄
