### ISSUE TITLE
Cursor object implementation

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#163]
Implement cursor object matches with PEP249

**Comment by Pradhvan** [comment]
This looks interesting 🤩 Is anyone working on this?

**Comment by Cheukting** [comment]
@Pradhvan It's something I intended to do maybe with @GavinMendelGleason in a few weeks. We can keep you in the loop if you wanna help.

**Comment by Pradhvan** [comment]
😊  @Cheukting please do keep me in a loop if possible and I would be more than happy to help out any way I can. I am interested in Databases so would be a great learning opportunity for me. 

😌  I anyway `PEP249 improvement` going to keep a check lookout on the PR's as they progress.

**Comment by Cheukting** [comment]
@Pradhvan we are going to have a chat about it sometime next week at our [community Discord server](https://discord.gg/Gvdqw97) Do you wanna join? Ping me at Discord :-)

**Comment by Pradhvan** [comment]
@Cheukting that would be great, I am already on the discord server will ping you. Please let me know the time, I can block the calendar seeing the timezone are hard to manage. 😄

**Comment by Cheukting** [comment]
Approach to the [cursor object in PEP249](https://www.python.org/dev/peps/pep-0249/#cursor-objects)

Create a WOQLCursor with the following approach:
1) fetchone / fetchany / fetch all - WOQLQuery wrapper
2) rollcount - Wait for server to return it at query result
3) description - get it from the result form the backend (description of the variables)
4) close - set an internal flag to disable the object
5) execute and executemany - similar to WOQLQuery execute
6) arraysize - getter setter of an internal attribute for setting the limit of the fetch many
7) setinputsize / setoutput size - To be implemented

**Comment by Pradhvan** [comment]
@Cheukting can I take up 1. fetchone / fetchany / fetch all - WOQLQuery wrapper? I would definitely need your help though.

**Comment by Cheukting** [comment]
@Pradhvan sure! Ping me anytime on Discord if you need to have a quick chat.
