### ISSUE TITLE
WOQLClient().true() incorrectly defined

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-client-python#166]
**Describe the bug**
`true()`'s semantics are obviously incorrect - probably a transcription error from the javascript client

**To Reproduce**
try to use `.true()`

**Expected behavior**
It should be defined as: 

```python
    def true(self):
        self._cursor["@type"] = "woql:True"
        return self
 ```

**Comment by Cheukting** [comment]
Fixed in https://github.com/terminusdb/terminusdb-client-python/commit/19d647776fca1e48c6b4714a2effe66ca9463b44
