### ISSUE TITLE
xsd:string is sensitive to prefixes on cast and shouldn't be

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb-client-python#173]
Ubuntu 18.04 running bootstrap version 4.1.2 in docker container, via python client:

>> WOQLQuery().cast('http:foo','xsd:string','v:Value').execute(client)
yields:
*** terminusdb_client.woqlclient.errors.APIError: {
  "api:message":"Error: key_has_unknown_prefix(\"http:foo\")\n  [47]  ...."}

>> WOQLQuery().cast('scm:foo','xsd:string','v:Value').execute(client)
yields:
*** terminusdb_client.woqlclient.errors.APIError: {
  "@type":"api:FrameErrorResponse",
  "api:error": {
    "@type":"api:BadCast",
    "api:type":"http://www.w3.org/2001/XMLSchema#string",
    "api:value":"'terminusdb:///schema#foo'"
  },
  "api:message":"The value 'terminusdb:///schema#foo' could not be cast as 'http://www.w3.org/2001/XMLSchema#string'",
  "api:status":"api:failure"
}

xsd:string should just take the string as-is (except perhaps deal with embedded '<' and '&') and ignore apparent prefixes.

**Comment by Cheukting** [comment]
@jbennettgit We will have a look at it, but the workaround right now is to use literal()

**Comment by Cheukting** [comment]
@GavinMendelGleason I think maybe we can add some options for cast() so it knows it contains a URL as string

**Comment by GavinMendelGleason** [comment]
Yes, this is not a genuine bug, just surprising behaviour because of the treatment of strings. We should have a look at reducing ambiguities.

**Comment by jbennettgit** [comment]
Could you point me at the references that describe this surprising treatment of strings?  I expect some hierarchy perhaps of string encodings such that, say, AnyURL might complain without http: if it isn’t well-formed if I cast to that type.  But plain ‘string’?  Really it should accept all comers of bytes.  Why is this not in fact a bug?

**Comment by Cheukting** [comment]
Ok @GavinMendelGleason maybe I will reopen and treat it as enhancement and we can see where it fits in our roadmap.

@jbennettgit I think it's a parsing limitation in the Python client so in fact, it's not a bug in the backend. I agree that we will have better handling of that and we will have a look. I will keep you post about the progression regarding this issue.

**Comment by Cheukting** [comment]
Short term fix: an extra flag to cast string in with literal
Long term fix: define custom Python class object to represent note object

**Comment by matko** [comment]
We'll revisit this issue when the document interface refactor is done.

**Comment by spl** [comment]
We're working on a new release, and this won't be relevant to that. Thanks!
