### ISSUE TITLE
WOQLClient.create_graph error

### ISSUE THREAD

**Issue by mrcjhurst** [terminusdb/terminusdb-client-python#174]
**Describe the bug**
client.create_graph throws an error.

**To Reproduce**
```
>>> client
<terminusdb_client.woqlclient.woqlClient.WOQLClient object at 0x7f7ce7e016d0>
>>> client.create_graph('instance', 'test-a-graph', 'create test graph')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../python3.9/site-packages/terminusdb_client/woqlclient/woqlClient.py", line 681, in create_graph
    self.conConfig.graph_url(graph_type, graph_id),
AttributeError: 'WOQLClient' object has no attribute 'conConfig'
```
**Expected behavior**
```
>>> client.create_graph('instance', 'test-a-graph', 'create test graph')
{'@type': 'api:CreateGraphResponse', 'api:status': 'api:success'}
```

**Error logs**
See above

**System information (please complete the following information):**
 - OS: Devuan Chimera/ceres 
 -  terminus-client-python 6.0
 - terminusdb-bootstrap Docker container

**Additional context**
Looks like conConfig has been depreciated but some references still remain in woqlClient.py

**Comment by Cheukting** [comment]
Thanks @mrcjhurst we will probably release a patch today.

**Comment by mrcjhurst** [comment]
@Cheukting thank you!   I have a reasonably different followup for delete_graph, but will wait for your patch.

**Comment by Cheukting** [comment]
The patch is now in there: https://github.com/terminusdb/terminusdb-client-python/tree/v0.6.1 it is supposed to be kicking off the GH action and the CI deploy to PyPI automatically but it seems GH action is not working at the moment.... please feel free to install the tag form GH locally (see [install from source](https://github.com/terminusdb/terminusdb-client-python#installation)) We will try to fix the GH action tomorrow.

**Comment by mrcjhurst** [comment]
looking good - thank you.

**Comment by Cheukting** [comment]
patch is released on PyPI: https://pypi.org/project/terminusdb-client/ now you can just do `pip install -U terminusdb-client`
