### ISSUE TITLE
gensym() needed

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb-client-python#175]
Quite often there is a need to generate several unique yet anonymous instances of a class, that is, the client doesn't care about their names but you want to make sure they are all separate).  Neither id_gen() nor unique() provide this function directly and require you to programmatically maintain some kind of global counter to pass as part of the key_list to ensure there is no collision with past ids.  And the client then needs to keep a record of the counter in the DB so inserts and queries during subsequent sessions continue to be unique.  The db server should provide this function.  In LISP, this function was called gensym (for generate a symbol); if no prefix was given it used 'G' and returned 'G00345', etc.

**Comment by GavinMendelGleason** [comment]
Random IDGen exposed in 77eb8ba - will close issue when it has also been added to Python client.

**Comment by Cheukting** [comment]
Fixed in https://github.com/terminusdb/terminusdb-client-python/commit/00e159aff38564efdd8cd82cece6075fb1d94f3f

**Comment by jbennettgit** [comment]
Just tried using it in the most recent python client (just pulled) but it complains that:

pp WOQLQuery().random_idgen("https://base.url",["page","1"],"v:obj_id").execute(client)
*** AttributeError: 'WOQLQuery' object has no attribute 'random_idgen'
