### ISSUE TITLE
Inserting value in datetime property now resulting in an error

### ISSUE THREAD

**Issue by MrRaymondLee** [terminusdb/terminusdb-client-python#189]
**Describe the bug**
Prior to 1.0.0, I was able to insert values to a datetime property.  Now it is returning an error "There was an error when schema checking"

**To Reproduce**
`
WOQL().insert("myTestDocInstance", "scm:TestDoc")
.property("date_created", WOQL().datetime(datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")))
.execute(client)
`

**Expected behavior**
Current date time inserted into the property. 

**Error logs**
{'@type': 'api:WoqlErrorResponse', 'api:error': {'@type': 'api:WOQLSchemaCheckFailure', 'api:witnesses': [{'@type': 'vio:PropertyWithUndefinedDomain', 'vio:message': {'@type': 'xsd:string', '@value': 'The property terminusdb:///schema#date_created has an undefined domain.'}, 'vio:property': {'@type': 'xsd:anyURI', '@value': 'terminusdb:///schema#date_created'}}]}, 'api:message': 'There was an error when schema checking', 'api:status': 'api:failure'}

**System information (please complete the following information):**
 - OS: Ubuntu 20
 -  terminus-client-python 1.0.0

**Comment by GavinMendelGleason** [comment]
Can you attach the schema so we can attempt to reproduce? @MrRaymondLee

**Comment by GavinMendelGleason** [comment]
Can not reproduce. I believe this was an actual schema violation.
