### ISSUE TITLE
WOQL ergonomics with new operators

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-client-python#203]
I'd like to be able to specify conjunction, disjunction and type annotation more conveniently in the query language. To this end I think we should use the operators `__and__` `__or__` and `__rxor__` to facilitate the construction of queries. 

For instance:

```python
WOQL().triple("v:X", "pred", "v:Y") & WOQL().triple("v:Y", "pred", "v:Z")

WOQL().triple("v:X", "pred0", "v:Y") | WOQL().triple("v:X", "pred1", "v:Y")

WOQL().triple("v:X", "pred0", "2012-10-13T00:00:00.000"^xsd.dateTime)
```

Currently we have `+` for conjunction but I think `+` should be interpreted as disjunction more naturally (and `*` as conjunction) so I'd prefer to deprecate.

The later should probably be facilitated by having a library `xsd` with every available type. This could help catch errors earlier and avoid silent failure as well as facilitating more sophisticated type marshalling from native python types (such as dates).

**Comment by Cheukting** [comment]
For the last one `WOQL().triple("v:X", "pred0", "2012-10-13T00:00:00.000"^xsd.dateTime)` is a bit complicated cause we need a new set of classes for the xsd types. For & and | I will make a PR in like 5 mins

**Comment by Cheukting** [comment]
For me and a few people using + already it's natural to add a bunch of query up with the + sign, I don't see the use case for the disjunction and conjunction yet I will hold up for if we have a 2.0 release

**Comment by Cheukting** [comment]
And for the xsd library we need to have this: https://github.com/terminusdb/terminusdb/issues/283
