### ISSUE TITLE
Add get_triple (and other triple stuff) back in action

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#240]
Right now the get_triple is taken out because the old logic is not compatible with v10 of the backend (see https://github.com/terminusdb/terminusdb-client-python/issues/236). We need to update that logic with someone who has the knowledge of the backend.

**Comment by spl** [comment]
Waiting on <https://github.com/terminusdb/terminusdb/issues/805>.

**Comment by rrooij** [comment]
Fixed in https://github.com/terminusdb/terminusdb-client-python/pull/345
