### ISSUE TITLE
Fix logic in WOQLView

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#241]
Now WOQLView is not available because the `result` that it is expecting is in the format of v4 of TerminusDB. We have to either convert the `result` we get from the current version (v10) to match with the old `result` or have the JS client update the component that works with v10

**Comment by spl** [comment]
@GavinMendelGleason, @Cheukting, @KittyJose, and @Francesca-Bit will discuss this.
