### ISSUE TITLE
[Dissicussion] Rename the command terminusdb to tdbp

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-client-python#242]
`terminusdb` is a command used by the backend cli, so to avoid confusion the click CLI tool in Python client is proposed to renamed as `tdbp` (my choice, feel free to propose others) Should be done in the next minor release.

I would rather to not rename it if it is not a must, cause I will have to go to all the tutorials and old demos (some could be video recordings) to change it (or make a remark about the change). I wonder if a user who is using both, can they rename this one as something else locally? 

Would like to hear more thought about it

**Comment by spl** [comment]
Perhaps the backend command should be `terminusdb-ctrl`.

**Comment by spl** [comment]
Python won't change.
