### ISSUE TITLE
WoQLQuery.when() does not exist anymore?

### ISSUE THREAD

**Issue by AstroChelonian** [terminusdb/terminusdb-client-python#245]
when I try to make  a query as follows

```python
qry = WoQLQuery().when(True, add_trpl)
``` 
in order to update my database using:

```python
client.update(qry.json(), ‘Database’)
```

I get the following error:

```bash
AttributeError: 'WOQLQuery' object has no attribute 'when'
```

**Comment by Cheukting** [comment]
Yes we took it off. Maybe it's not working anymore? Can't remember the reason why. Do you remember @GavinMendelGleason?

**Comment by AstroChelonian** [comment]
This should not be used to update the database, the user should use the web interface instead.

**Comment by GavinMendelGleason** [comment]
`when` does not exist anymore.
