### ISSUE TITLE
Path query with least/most fails with type error

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb-client-python#257]
**Describe the bug**
Performing a path query with least/most fails. Using the same query with the + quantifiers works with the same query in other respects.

**To Reproduce**
1. Go to TerminusX
2. Have model where a path query can be performed with edge property names known
2. Click on Data Product Explorer
3. Enter queries
4. Open Browser console --> Network information --> clear cache
4. Press Run
4. See error as the response (HTTP 400)

Non-working query (note the *{1,2}*):
```
WOQL.and(
  WOQL.triple("v:person","rdf:type","@schema:Capability"),
  WOQL.triple("v:circle","rdf:type","@schema:Gap"),
  WOQL.path("v:person","((capability_userstory|userstory_gap){1,2})","v:circle","v:path_var5")
  )
```

Working query (note the *+*):
```
WOQL.and(
  WOQL.triple("v:person","rdf:type","@schema:Capability"),
  WOQL.triple("v:circle","rdf:type","@schema:Gap"),
  WOQL.path("v:person","((capability_userstory|userstory_gap)+)","v:circle","v:path_var5")
  )
```

**Expected behavior**
I expected to get the same result between both queries

**Screenshots**
See error message below (the error message is not reported in TerminusX, and just fails silently, showing the result of the previous query instead of failing).
```
{
  "api:message":"Type error for '1'/0 which should be evaluable",
  "api:status":"api:failure",
  "system:witnesses": [
    {
      "@type":"vio:ViolationWithDatatypeObject",
      "vio:literal":"'1'/0",
      "vio:message":"Type error for '1'/0 which should be evaluable",
      "vio:type":"evaluable"
    }
  ]
}
```

**Info (please complete the following information):**
 - OS: Microsoft Edge (chromium)
 - TerminusX
 - 
**Additional context**

**Comment by Cheukting** [comment]
Hey, @hoijnet thanks for the issue :-) While I was investigating, I realized the code you provided is in js (I take `WOQL.and` as a hint). Is it a problem that exists in both clients?

**Comment by Cheukting** [comment]
I have tried testing the query `WOQLQuery().path("v:person","((capability_userstory|userstory_gap){1,2})","v:circle","v:path_var5")` and the result is way worse, the Python client cannot translate the query at all (I think it end up in some weird recursion loop) Will look deeper into it. No problem with the query with the `+` tho

**Comment by hoijnet** [comment]
Correct, it's in the javascript client, but the error seems to be one the server side (or in the translation to the server side). Have not tested in Python. And as you mention, the + notation then seems to work in both Javascript and Python.

Seems to be the same across then, but what the error in the Javascript client is I don't know :-) So might be multiple problems if you faced local issues in Python.

**Comment by GavinMendelGleason** [comment]
The JS client bug is just the parser emitting the wrong type of object. There may be additional bugs which don't come up because it doesn't parse it correctly though :D

**Comment by Cheukting** [comment]
@GavinMendelGleason I found the bug in the Python client, it was a one-off in one of those complicated pattern parsing. Now the query translated to this json:
```
{"@type": "Path", "object": {"@type": "Value", "variable": "circle"}, "path": {"@type": "Value", "variable": "path_var5"}, "pattern": {"@type": "PathTimes", "from": 1, "times": {"@type": "PathOr", "or": [{"@type": "PathPredicate", "predicate": "capability_userstory"}, {"@type": "PathPredicate", "predicate": "userstory_gap"}]}, "to": 2}, "subject": {"@type": "NodeValue", "variable": "person"}}
```
If it looks correct, I will put in the fix :-)

**Comment by hoijnet** [comment]
The issue was transferred from the main repo, so @spl maybe a twin issue should be created in the javascript repo too (maybe it has already)?
