### ISSUE TITLE
Track data version across requests

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-client-python#259]
See https://github.com/terminusdb/terminusdb/issues/248 for the server issue.

Operation:
* The client will read the commit ID from responses.
* The client will submit the last commit ID in requests.

Notes:
* The server will only check the commit ID on the `/api/document` and `/api/woql` endpoints, but the client can include the commit ID header on every request, which the server will ignore.

**Comment by spl** [comment]
This is now in: terminusdb/terminusdb#911

**Comment by Cheukting** [comment]
It's in dev and will be deploy in production
