### ISSUE TITLE
Rename WOQLClient

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-client-python#260]
The client is strictly related to WOQL, so it should be renamed. We need to think about the name and how to do it.

**Comment by rrooij** [comment]
Can we consider this fixed since commit: https://github.com/terminusdb/terminusdb-client-python/commit/79371515faae6295224d5a303fee6c67e0b88eb5 ?

**Comment by GavinMendelGleason** [comment]
Yes
