### ISSUE TITLE
Update for WOQL schema changes

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-client-python#267]
Various document query elements changed recently. They need to be updated in the client.

* See also https://github.com/terminusdb/terminusdb-client-js/issues/78 for the JavaScript issue.
* See https://github.com/terminusdb/terminusdb/commit/1c75eef9365fdb50abee013d502f89ab21082867 for a large change to `json_woql.pl` that describes some, if not all, changes.
* See the current [WOQL schema](https://github.com/terminusdb/terminusdb/blob/main/src/terminus-schema/woql.json).

**Comment by spl** [comment]
@Neelterminusdb Would it make sense for you to work on this issue at the same time as <https://github.com/terminusdb/terminusdb-client-js/issues/78>, since these issues involve the same changes?

**Comment by spl** [comment]
From my reading of <https://github.com/terminusdb/terminusdb/commit/1c75eef9365fdb50abee013d502f89ab21082867?w=1>, I think these need to change:
* `ReadObject` -> `ReadDocument`
  * `document_uri` -> `identifier`
* `UpdateObject` -> `UpdateDocument`
* `DeleteObject` -> `DeleteDocument`
  * `document_uri` -> `identifier`

**Comment by spl** [comment]
Refer to #268 for the relevant Python code and schema.

**Comment by Cheukting** [comment]
It's ok, I am on it

**Comment by spl** [comment]
More changes were made to the WOQL schema. Can we please add those to the client to close this issue? See [#821](https://github.com/terminusdb/terminusdb/pull/821/files#diff-dbf34ad9a4214468d546d66fc6fba951c07aa132d092afe8d9cafffba581b3bd).

**Comment by Cheukting** [comment]
Is it just `insert document` that need to be added (that what I see) @spl @GavinMendelGleason ?

**Comment by spl** [comment]
> Is it just `insert document` that need to be added (that's what I see) @spl @GavinMendelGleason ?

@Cheukting I think that's the main one. There is now an optional `identifier` for `UpdateDocument`: I'm not sure if that makes a difference to you.

**Comment by Cheukting** [comment]
> > Is it just `insert document` that need to be added (that's what I see) @spl @GavinMendelGleason ?
> 
> @Cheukting I think that's the main one. There is now an optional `identifier` for `UpdateDocument`: I'm not sure if that makes a difference to you.

That's already implemented in the PR
