### ISSUE TITLE
Documentation error on resources

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-client-python#276]
```python
client.resource(ResourceType.META)
'<team>/<db>/<repo>/_meta' 
```

Should be deleted - it is redundant and wrong.  The previous one which says `<team>/<db>/_meta` is correct

![Screenshot from 2021-12-10 17-53-26](https://user-images.githubusercontent.com/1993386/145611650-90e5dcc9-1ae5-47ed-940a-d84fb7606822.png)

**Comment by Cheukting** [comment]
Fix has been merged and released
