### ISSUE TITLE
 Remove connect function and remove it from the docs as well

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb-client-python#286]
We don't need it. It is an extra step that is unnecessary since we don't have persistent connections. We are stateless.

**Comment by Cheukting** [comment]
One big thing I would consider is backward compatibility and also right now we need it to connect to a specific database. Plus, it will ping the server to check if it exists (see dev branch) and if the db exists. So I cannot agree with the point for it being unnecessary.

**Comment by spl** [comment]
The issue was created because the connect function in the JavaScript isn't needed, but it is used in Python, and it is documented. So, we will not change this now.
