### ISSUE TITLE
Use “data version” instead of “version”

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-client-python#289]
I think it would be better to use the term “data version” (e.g. `data_version` or `get_data_version`) instead of just “version” throughout the code and comments. First, “version” is too ambiguous. Especially with software, I'd guess most people would first think it refers to the version of the library. Second, the use of “data version” helps to align the Python client documentation with the HTTP API documentation.

**Comment by Cheukting** [comment]
I don't really mind the naming so much. For me it was just lext typing and since version is used in the document operations so it was pretty obvious to me. But anyway, I can add the "data" in the version with just search and paste and can be easily done if desired.

**Comment by Cheukting** [comment]
merged, will be in release
