### ISSUE TITLE
Throw clear exception when WOQLClient is initialized without DB

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb-client-python#86]
When a WOQLClient is initialized and a query is executed without a database, the following error appears:

```
woqlclient.errors.InvalidURIError: Invalid argument to Undefined, TerminusDB Id is not a valid Terminus DB API endpoint
```

It should probably be clearer that a DB should be passed to `WOQLClient` before a proper query can be executed.

**Comment by Cheukting** [comment]
Now (version 0.1.1) a database is required to initialize a WOQLClient object.
