### ISSUE TITLE
camelCase to snake_case

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb-client-python#89]
snake_case is the main convention according to PEP. Should we adhere to it?

https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

**Comment by Cheukting** [comment]
Yes, we still have a lot to change to make the code follow PEP8. Especially the naming convention for Python: snake_case for variable and function name, camelCase for class names.

**Comment by Cheukting** [comment]
Most of it is fixed in version 0.1.1. The will keep tidy up the rest. Consider this done (90%)
